### ISSUE TITLE
whiteboard loading error: socket.io

### ISSUE THREAD

**Issue by mygurukool** [mygurukool/schoolUI#1]
- [x]  Loading of whiteboard is not stable
- [x]  The url is static (https://wbo.ophir.dev/boards/VidyamandirClass8Aharsh@gmail.com#28112021) instead should be dynamic 
https://wbo.ophir.dev/boards/<schoolname_classname:teacher/ student Id/ email/#timestamp>

**Comment by mygurukool** [comment]
screenshot ![image](https://user-images.githubusercontent.com/66110311/151017426-bbe16072-e06d-40e2-9d08-dcfaa959791f.png)

**Comment by harshmewada** [comment]
Generation Of Whiteboard url was the problem, found out that the whiteboard provider doesn't accept special characters or ` /` i the the url

**Comment by mygurukool** [comment]
no socket errors
