### ISSUE TITLE
whiteboard URL

### ISSUE THREAD

**Issue by mygurukool** [mygurukool/schoolUI#22]
whiteboard URL is hardcoded to 
![image](https://user-images.githubusercontent.com/66110311/152777095-4b4d4263-a2d0-4db2-aa73-6f244e052f13.png)

![image](https://user-images.githubusercontent.com/66110311/152777927-1d10d6ce-653f-4cce-ae26-a4bfaf1792ed.png)

https://wbo.ophir.dev/boards/VidyamandirClass8A${userName}#28112021

instead the actual logic should be:
https://wbo.ophir.dev/boards/${schoolName}${userName}#{date_timestamp}

in case of school is not from mygurukool then schoolname should be GoogleClass or MsTeams

**Comment by harshmewada** [comment]
Changed To Dynamic Url

**Comment by harshmewada** [comment]
https://github.com/mygurukool/schoolUI/tree/e36e7fea9513c64c018f9cb450ed1d3f5ade5dfb

**Comment by mygurukool** [comment]
impl
