### ISSUE TITLE
Whiteboard loading errors

### ISSUE THREAD

**Issue by mygurukool** [mygurukool/schoolUI#26]
![image](https://user-images.githubusercontent.com/66110311/153064386-3893fc64-bdb0-4e11-9d22-5b45b31c566d.png)

**Comment by harshmewada** [comment]
https://github.com/mygurukool/schoolUI/commit/e36e7fea9513c64c018f9cb450ed1d3f5ade5dfb

**Comment by mygurukool** [comment]
issue still persists 
![image](https://user-images.githubusercontent.com/66110311/153847056-eefa148f-94d9-430f-b128-448ed07b3fbf.png)

**Comment by mygurukool** [comment]
impl
