### ISSUE TITLE
UI Responsive: Conference/ white board - tablet 

### ISSUE THREAD

**Issue by mygurukool** [mygurukool/schoolUI#47]
Alignment of  Conference/ white board is improper with tablet versions( Dhairya is already working on Mobile)

Working from  Large Screen 1280x800 and all laptop models

Misalignment egs:

Max mode
![image](https://user-images.githubusercontent.com/66110311/154960980-38fdfdaa-08a5-4daa-87d1-e4649087fda9.png)

minimize mode
![image](https://user-images.githubusercontent.com/66110311/154961092-407005cc-91ed-4f52-8e81-038d08252ce1.png)

![image](https://user-images.githubusercontent.com/66110311/154961262-b7914a47-f910-45f9-a3d8-8b858b9e9b19.png)

![image](https://user-images.githubusercontent.com/66110311/154961339-053c14cc-ce10-4fbd-bbcd-03f17d981c72.png)

**Comment by dhairyamodh** [comment]
from iPad Pro 12.9 inch size tablet we will use split screen and ipade 10.5 inch and below without split screen

**Comment by mygurukool** [comment]
fixed
