### ISSUE TITLE
Teacher Assignments: File Upload button/ accordion collapse+ expand

### ISSUE THREAD

**Issue by mygurukool** [mygurukool/schoolUI#60]
As a teacher, i upload the files from edit assignment screen, therefore **upload button** next to the exercise material should not be visible for teacher (but visible only for student)

Accordion collapse + expand has no functionality unlike for student, therefore the arrow buttons can only confuse teacher

![image](https://user-images.githubusercontent.com/66110311/157002333-768a1ee1-06f7-448c-bdc9-9a0127715a71.png)

**Comment by harshmewada** [comment]
https://github.com/mygurukool/schoolUI/commit/c1f0850ddc8b83d48996f37c90c8f2cd4268a246

**Comment by mygurukool** [comment]
impl
