### ISSUE TITLE
lang translation: Language menu

### ISSUE THREAD

**Issue by mygurukool** [mygurukool/schoolUI#66]
Text of **Languages** on language menu should be the respective language

![image](https://user-images.githubusercontent.com/66110311/157066894-228fda07-8c27-42fa-9f14-7907d9b8351f.png)
 
eg:
English
Deutsch
हिन्दी
Français
ગુજરાતી

**Comment by dhairyamodh** [comment]
Language menu conf. can be done in file src/utils/languages.json
