### ISSUE TITLE
End Conf leads to empty page 

### ISSUE THREAD

**Issue by mygurukool** [mygurukool/schoolUI#72]
end the Conf by pressing **End button/ Leave** leads to empty page. 

test case:
- Opened Conf
- used it in max 
- End meeting with **End button/ Leave** of jitsi conf 

![image](https://user-images.githubusercontent.com/66110311/157491552-6d65f5d6-558f-412f-853b-23066c82c5c0.png)

**Comment by mygurukool** [comment]
doesnt work

**Comment by harshmewada** [comment]
https://github.com/mygurukool/schoolUI/commit/8d5cd9ff575382839d213555bd6025e02df36d5e

**Comment by mygurukool** [comment]
impl
