### ISSUE TITLE
Invite ppl to Group: Stale link

### ISSUE THREAD

**Issue by mygurukool** [mygurukool/schoolUI#79]
- A stale invite link / from past is being displayed. ( i remember to have been already fixed, but ... )

![image](https://user-images.githubusercontent.com/66110311/158430025-28a228ed-1fae-4118-889b-e6c2395564cc.png)

- Invite button is always enabled, leading to confusion:
    - Enabled when no user is invited
    - entering email id: as per the flow, after entering email id, *Enter* must be pressed to be qualified as valid email, but as the invite button is always enabled, its confusing, what else to be done
![image](https://user-images.githubusercontent.com/66110311/158430780-611ec0cd-6831-466a-a12f-72f492d8ce91.png)

**Comment by harshmewada** [comment]
https://github.com/mygurukool/schoolUI/commit/8d5cd9ff575382839d213555bd6025e02df36d5e

**Comment by mygurukool** [comment]
impl
