### ISSUE TITLE
Assignment attachment: View and Download PDF

### ISSUE THREAD

**Issue by mygurukool** [mygurukool/schoolUI#8]
**Describe the bug**
View or Download of assignment attachment is not working. 

**To Reproduce**
1. Go to 'assignment attachment '
2. Click on 'view' or 'download' button
3. nothing happens
4. See error in console

**Comment by harshmewada** [comment]
Gridfs cofiguration was the problem.

[https://github.com/mygurukool/schoolAPI/commit/509e8ec8c9bb57d8990c40eb23c45d4086b43a2c](url)

**Comment by mygurukool** [comment]
tested
