### ISSUE TITLE
Create assignment error: Add students

### ISSUE THREAD

**Issue by mygurukool** [mygurukool/schoolUI#82]
- Created new group (class)
- created new subject
- Add assignment: throw the following errors, No Student have been invited

![image](https://user-images.githubusercontent.com/66110311/158989812-2c86de1f-1c32-4035-94ba-e16167801dde.png)

**Comment by harshmewada** [comment]
https://github.com/mygurukool/schoolUI/commit/8d5cd9ff575382839d213555bd6025e02df36d5e

**Comment by mygurukool** [comment]
fixed
